"""claude relationships

Revision ID: 5c9cae8a42aa
Revises: dc193937e082
Create Date: 2024-05-02 16:22:04.276936

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '5c9cae8a42aa'
down_revision = 'dc193937e082'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('threads', schema=None) as batch_op:
        batch_op.create_foreign_key(batch_op.f('fk_threads_author_id_users'), 'users', ['author_id'], ['id'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('threads', schema=None) as batch_op:
        batch_op.drop_constraint(batch_op.f('fk_threads_author_id_users'), type_='foreignkey')

    # ### end Alembic commands ###
