"""add updated at to threads

Revision ID: 9381d1ec1bf1
Revises: 5c9cae8a42aa
Create Date: 2024-05-03 17:20:55.068224

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '9381d1ec1bf1'
down_revision = '5c9cae8a42aa'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('threads', schema=None) as batch_op:
        batch_op.add_column(sa.Column('last_updated', sa.Integer(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('threads', schema=None) as batch_op:
        batch_op.drop_column('last_updated')

    # ### end Alembic commands ###
